### PR TITLE
Fix some PDF related issues

### PR DESCRIPTION
**Pull request by Sinclair19**
1. f0d465091f33726bf6f1be73a7e2fbc0685e108b Fixed the `./build-meta.bash: 7: [[: not found` error occurring in both `pnpm dev` and `build` processes.

2. 623e35c7fe54208627f3b9fe563417ec9a627ade Resolved an issue where navigating to another view (PDF, both, log) and clicking on a path did not automatically redirect to the editor view, which was unintended behavior.

3. fa7ade7c76086a09e4097384d709e64c2e9f9295 Fixed issues with PDF display and the functionality of the both view. Most modern desktop browsers support using iframes to display PDF files, which is not supported by mobile browsers. However this is still a big improvement over the previous not usable state (Before the pdf view will freeze the whole page except the nav bar and not work on both view). The pdfslick dependency was retained and can be removed in the future.

### CODE REVIEW

**Review by zjkmxy — APPROVED** [review]
LGTM. Let me test before merge.

**Comment by zjkmxy** [comment]
> which is not supported by mobile browsers.
I hope this does not break things. I'm not able to test it on my phone or iPad before the code is released.

**Comment by Sinclair19** [comment]
> > which is not supported by mobile browsers.
> 
> I hope this does not break things. I'm not able to test it on my phone or iPad before the code is released.

I think it won't be a big problem.
You can have a try of this demo website. It provides different ways to embed pdf, which include a example iframe.
https://pdfobject.com/static/
On mobile Chrome, it just shows a button to open/download it.

**Comment by zjkmxy** [comment]
> > > which is not supported by mobile browsers.
> > 
> > 
> > I hope this does not break things. I'm not able to test it on my phone or iPad before the code is released.
> 
> I think it won't be a big problem. You can have a try of this demo website. It provides different ways to embed pdf, which includes iframe. https://pdfobject.com/static/ On Android Chrome/Edge, it just shows a button to open/download it. On Android Firefox, it can be displayed properly.

It also works fine on iPad as an installed PWA. I think it's good.

**Comment by Sinclair19** [comment]
Great, I think after it being released and tested, we can remove all PDFSlick related dependency. I can make another PR to do this.

**Comment by zjkmxy** [comment]
> Great, I think after it being released and tested, we can remove all PDFSlick related dependency. I can make another PR to do this.

I have already done. But thanks.

**Pull request merged**
