### PR TITLE
Qr-code display for safebag and backdrop around existing ones

### PR DESCRIPTION
**Pull request by AnoldGH**
- Adds qr-code display for safebag
- Wraps qr-code displays for certificate and trust anchors so that it's more friendly to users in general
- [Next step] Adds qr-reader for certificate and safebag

### CODE REVIEW

**Comment by zjkmxy** [comment]
Unfortunately adding QR code for safebags on the website does not help. The safebag is obtained **somewhere** and then inputed to workspace for bootstrap. So the most important part is that the **somewhere** should support QR cde display.

**Comment by AnoldGH** [comment]
> Unfortunately adding QR code for safebags on the website does not help. The safebag is obtained **somewhere** and then inputed to workspace for bootstrap. So the most important part is that the **somewhere** should support QR cde display.

I see. That makes very sense.

This update also wrapped backdrop components around existing QR displays, so they are shown only when the button is pressed and in full-screen. This I think makes using QR codes much more friendly for mobile users. Let me know if I should create a separate PR for it.

**Comment by zjkmxy** [comment]
> Let me know if I should create a separate PR for it.

If that is the case, let me review it and get it merged

**Review by zjkmxy — APPROVED** [review]
LGTM

**Pull request merged**
