### PR TITLE
Implemented multi-level navigation bar for `Editor` and `Chat`

### LINKED ISSUE #84: Use multi-level navigation bar
Put `Editor` and `Chat` under `Workspace` tab and disable them when there is no workspace loaded.

### PR DESCRIPTION
**Pull request by AnoldGH**
- Added `level` to `RouteItem` to represent indentation
    - Added `trigger` to `RouteItem` to achieve conditional rendering
    - Used `booted` from NDN context as triggers to `Editor` and `Chat`
resolves #84

### CODE REVIEW

**Comment by zjkmxy** [comment]
Thank you for your contribution, but the same part is also modified in #100. Let me see if we can get their PR merged first.

**Review by zjkmxy — APPROVED** [review]
LGTM. Thanks.

**Comment by zjkmxy** [comment]
Just realized you did not modify the mobile view (displayed with narrow width).

**Comment by AnoldGH** [comment]
> Just realized you did not modify the mobile view (displayed with narrow width).

My bad, I overlooked the mobile view on this one. I just opened a new PR #107 that hides `Editor` and `Chat` in mobile view following the same rules (using `booted`). For now, it's just hiding and re-enabling the buttons - so no indentations or anything.

**Pull request merged**
